/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: "category",
      label: "Demos",
      link: {
        type: "generated-index",
        title: "Showcases of the theme plugin",
        slug: "/demo",
      },
      items: [
        {
          type: "category",
          label: "JSON Schema Viewer",
          link: {
            type: "generated-index",
            title: "JSON Schema Viewer showcases",
            slug: "/demo/viewer",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "demo-viewer",
            },
          ],
        },
        {
          type: "category",
          label: "Real word examples",
          items: [
            {
              type: "link",
              label: "Box File Schema example",
              href: "/boxFileSchema",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "📖 API Reference",
      link: {
        type: "generated-index",
        title: "📖 API Reference",
        slug: "/api",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "api",
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
    tutorialSidebar: [
      {
        type: 'category',
        label: 'Tutorial',
        items: ['hello'],
      },
    ],
     */
}
